name: Badminton Court Booking

on:
  schedule:
    - cron: '0 17 * * 1-5'  # Weekdays at 17:00 UTC (00:00 Bangkok time)
  repository_dispatch:
    types: [booking-trigger]
  workflow_dispatch:
    inputs:
      booking_time:
        description: 'Time slot to book (format: HH:MM-HH:MM)'
        required: false
        default: '18:00-19:00'

jobs:
  book-court:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run booking script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          CARD_ID: ${{ secrets.CARD_ID }}
          SLOT_ID: ${{ secrets.SLOT_ID }}
          CONTACT: ${{ secrets.CONTACT }}
          BOOKING_TIME: ${{ github.event.client_payload.booking_time || github.event.inputs.booking_time || '18:00-19:00' }}
        run: node booking-script.js