name: Deploy UI

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create .env file with secrets
        run: |
          cd ui
          echo "VITE_TOKEN=${{ secrets.VITE_TOKEN }}" > .env
          echo "VITE_DEVICE_ID=${{ secrets.VITE_DEVICE_ID }}" >> .env
          echo "VITE_CARD_ID=${{ secrets.VITE_CARD_ID }}" >> .env
          
      - name: Install Dependencies
        run: |
          cd ui
          npm install
          
      - name: Build
        run: |
          cd ui
          npm run build || (cat /home/runner/.npm/_logs/*-debug.log && exit 1)
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ui/dist
          branch: gh-pages